### PR TITLE
Protocol2 changes, initial support includes Alex in bypass, ADC0 only.

### PR DESCRIPTION
**Pull request by n1gp**
Hi Vasiliy,

Here's a PR for initial support for protocol2.
I've tested it on a Hermes ANAN10 and an Orion2 ANAN-7000DLEII

It supports up to 8 RX depending on the firmware, Orion2 soon to have 8 RX.

Hope the merge looks OK.

Happy 4th!

-Rick / N1GP

### CODE REVIEW

**Review by k3it — COMMENTED** [review]
This looks very good. thank you for adding protocol 2 support.  Before I merge, did you verify that the protocol 1 still works as before with the older  receivers/firmware?

**Comment by n1gp** [comment]
I did on a Hermes ANAN10.

Give me a day or so and I'll verify P1 on my ANAN7000, will get back to you...

________________________________

**Comment by n1gp** [comment]
Needed to add the Orion2 to the Protocol1 case, but testing on my ANAN7000 looks good.
The above change 7ebb789 has the final update. Not sure if this got put into this PR or not??

**Comment by k3it** [comment]
@n1gp I merged/recompiled and published https://github.com/k3it/HermesIntf/releases/download/v21.7.18/HermesIntf-21.7.18.zip   When you have time can you please verify that this binary works with protocol 2 h/w?  (no hermes hardware here at the moment).  tnx 73 K3IT

**Comment by n1gp** [comment]
It tests good on my Hermes (ANAN10) and Orion2 (ANAN7000).

You may want to add Orion2 to the list, also currently most HPSDR P2 supports only 4 RX except Hermes & (ANAN10) only 2 RX.

I plan to release new P2 firmware for Orion1/2 and Angelia to support 8 RX sometime before summer end.

73, Rick / N1GP

________________________________

**Comment by k3it** [comment]
thanks.  I added a note to the Release page 

https://github.com/k3it/HermesIntf/releases/tag/v21.7.18

**Pull request merged**
